name: track-generator
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - alsa-lib=1.2.8=h166bdaf_0
  - anyio=4.6.2.post1=pyhd8ed1ab_0
  - aom=3.5.0=h27087fc_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py311h5eee18b_0
  - arrow=1.3.0=py311h06a4308_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py311h06a4308_0
  - attr=2.5.1=h166bdaf_1
  - attrs=24.2.0=py311h06a4308_0
  - babel=2.11.0=py311h06a4308_0
  - backports=1.1=pyhd3eb1b0_1
  - backports.functools_lru_cache=2.0.0=pyhd8ed1ab_0
  - beautifulsoup4=4.12.3=py311h06a4308_0
  - binutils=2.40=h1680402_0
  - binutils_impl_linux-64=2.40=h5293946_0
  - binutils_linux-64=2.40.0=hc2dff05_2
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - bottleneck=1.4.2=py311hf4808d0_0
  - brotli=1.0.9=h5eee18b_8
  - brotli-bin=1.0.9=h5eee18b_8
  - brotli-python=1.0.9=py311h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.2.25=h06a4308_0
  - cached-property=1.5.2=py_0
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.16.0=ha61ee94_1014
  - certifi=2025.1.31=pyhd8ed1ab_0
  - cffi=1.17.1=py311h1fdaa30_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - colorama=0.4.6=py311h06a4308_0
  - comm=0.2.1=py311h06a4308_0
  - contourpy=1.2.0=py311hdb19cb5_0
  - cuda=12.4.1=hb982923_0
  - cuda-cccl=12.4.127=0
  - cuda-command-line-tools=12.4.1=0
  - cuda-compiler=12.4.1=h6a678d5_1
  - cuda-cudart=12.4.127=0
  - cuda-cudart-dev=12.4.127=0
  - cuda-cuobjdump=12.4.127=0
  - cuda-cupti=12.4.127=0
  - cuda-cuxxfilt=12.4.127=0
  - cuda-driver-dev=12.4.127=0
  - cuda-gdb=12.4.127=0
  - cuda-libraries=12.4.1=0
  - cuda-libraries-dev=12.4.1=h06a4308_1
  - cuda-nsight=12.4.127=0
  - cuda-nvcc=12.4.131=0
  - cuda-nvdisasm=12.4.127=0
  - cuda-nvml-dev=12.4.127=0
  - cuda-nvprof=12.4.127=0
  - cuda-nvprune=12.4.127=0
  - cuda-nvrtc=12.4.127=0
  - cuda-nvrtc-dev=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-nvvp=12.4.127=0
  - cuda-opencl=12.4.127=0
  - cuda-opencl-dev=12.4.127=0
  - cuda-profiler-api=12.4.127=0
  - cuda-runtime=12.4.1=0
  - cuda-sanitizer-api=12.4.127=0
  - cuda-toolkit=12.4.1=hb982923_0
  - cuda-tools=12.4.1=h06a4308_1
  - cuda-version=11.8=hcce14f8_3
  - cuda-visual-tools=12.4.1=h06a4308_1
  - cudatoolkit=11.8.0=h6a678d5_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.6.7=py311h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=py311h06a4308_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.3=h6a678d5_0
  - ffmpeg=5.1.2=gpl_h8dda1f0_106
  - fftw=3.3.10=nompi_hf1063bd_110
  - filelock=3.13.1=py311h06a4308_0
  - flit-core=3.10.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonts-conda-forge=1=0
  - fonttools=4.51.0=py311h5eee18b_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freeglut=3.2.2=h9c3ff4c_1
  - freetype=2.12.1=h4a9f257_0
  - fsspec=2024.9.0=pyhff2d567_0
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gcc_linux-64=11.2.0=h5c386dc_2
  - gds-tools=1.9.1.3=0
  - gettext=0.22.5=he02047a_3
  - gettext-tools=0.22.5=he02047a_3
  - giflib=5.2.2=h5eee18b_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py311hc9b5ff0_0
  - gnutls=3.7.9=hb077bed_0
  - graphite2=1.3.14=h295c915_1
  - gst-plugins-base=1.22.0=h4243ec0_2
  - gstreamer=1.22.0=h25f0c4b_2
  - gstreamer-orc=0.4.40=hb9d3cd8_0
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - gxx_linux-64=11.2.0=hc2dff05_2
  - h11=0.14.0=py311h06a4308_0
  - h2=4.1.0=pyhd8ed1ab_0
  - harfbuzz=6.0.0=h8e241bc_0
  - hdf5=1.14.0=nompi_hb72d44e_103
  - hpack=4.0.0=py_0
  - httpcore=1.0.2=py311h06a4308_0
  - httpx=0.27.0=py311h06a4308_0
  - hyperframe=6.0.1=pyhd3eb1b0_0
  - icu=70.1=h27087fc_0
  - idna=3.7=py311h06a4308_0
  - imageio=2.36.0=pyh12aca89_1
  - imageio-ffmpeg=0.5.1=pyhd8ed1ab_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib_metadata=8.5.0=hd8ed1ab_0
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.29.5=py311h06a4308_0
  - ipython=8.27.0=py311h06a4308_0
  - ipywidgets=8.1.2=py311h06a4308_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jack=1.9.22=h11f4161_0
  - jasper=2.0.33=h0ff4b12_1
  - jedi=0.19.1=py311h06a4308_0
  - jinja2=3.1.4=py311h06a4308_1
  - jpeg=9e=h5eee18b_3
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonpointer=3.0.0=py311h38be061_1
  - jsonschema=4.23.0=py311h06a4308_0
  - jsonschema-specifications=2023.7.1=py311h06a4308_0
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_0
  - jupyter=1.0.0=py311h06a4308_9
  - jupyter-lsp=2.2.0=py311h06a4308_0
  - jupyter_client=8.6.0=py311h06a4308_0
  - jupyter_console=6.6.3=py311h06a4308_0
  - jupyter_core=5.7.2=py311h06a4308_0
  - jupyter_events=0.10.0=py311h06a4308_0
  - jupyter_server=2.14.1=py311h06a4308_0
  - jupyter_server_terminals=0.4.4=py311h06a4308_1
  - jupyterlab=4.2.5=py311h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.27.3=py311h06a4308_0
  - jupyterlab_widgets=3.0.10=py311h06a4308_0
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py311h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=3.0=h295c915_0
  - libaec=1.1.3=h59595ed_0
  - libasprintf=0.22.5=he8f35ee_3
  - libasprintf-devel=0.22.5=he8f35ee_3
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libcap=2.66=ha37c62d_0
  - libcblas=3.9.0=8_h3b12eaf_netlib
  - libclang=15.0.7=default_h127d8a8_5
  - libclang13=15.0.7=default_h5d6823c_5
  - libcublas=12.4.5.8=0
  - libcublas-dev=12.4.5.8=0
  - libcufft=11.2.1.3=0
  - libcufft-dev=11.2.1.3=0
  - libcufile=1.9.1.3=0
  - libcufile-dev=1.9.1.3=0
  - libcups=2.3.3=h36d4200_3
  - libcurand=10.3.5.147=0
  - libcurand-dev=10.3.5.147=0
  - libcurl=8.9.1=h251f7ec_0
  - libcusolver=11.6.1.9=0
  - libcusolver-dev=11.6.1.9=0
  - libcusparse=12.3.1.170=0
  - libcusparse-dev=12.3.1.170=0
  - libdb=6.2.32=h6a678d5_1
  - libdeflate=1.17=h5eee18b_1
  - libdrm=2.4.123=hb9d3cd8_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.10=h28343ad_4
  - libexpat=2.6.3=h5888daf_0
  - libffi=3.4.4=h6a678d5_1
  - libflac=1.4.3=h59595ed_0
  - libgcc=14.2.0=h77fa898_1
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgcrypt=1.11.0=h4ab18f5_1
  - libgettextpo=0.22.5=he02047a_3
  - libgettextpo-devel=0.22.5=he02047a_3
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libglib=2.78.4=hdc74915_0
  - libglu=9.0.0=hf484d3e_1
  - libgomp=14.2.0=h77fa898_1
  - libgpg-error=1.50=h4f305b6_0
  - libhwloc=2.9.0=hd6dc26d_0
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblapack=3.9.0=8_h3b12eaf_netlib
  - liblapacke=3.9.0=8_h3b12eaf_netlib
  - libllvm14=14.0.6=hecde1de_4
  - libllvm15=15.0.7=hadd5161_1
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=12.2.5.30=0
  - libnpp-dev=12.2.5.30=0
  - libnsl=2.0.0=h5eee18b_0
  - libnvfatbin=12.4.127=0
  - libnvfatbin-dev=12.4.127=0
  - libnvjitlink=12.4.127=0
  - libnvjitlink-dev=12.4.127=0
  - libnvjpeg=12.3.1.117=0
  - libnvjpeg-dev=12.3.1.117=0
  - libogg=1.3.5=h27cfd23_1
  - libopencv=4.7.0=py311h7a0761e_1
  - libopus=1.3.1=h5eee18b_1
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=15.2=hb675445_0
  - libprotobuf=3.21.12=hfc55251_2
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.18=h7b6447c_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libsystemd0=252=h2a991cd_0
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libtool=2.4.7=he02047a_1
  - libudev1=253=h0b41bf4_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.18.0=h0b41bf4_0
  - libvorbis=1.3.7=h7b6447c_0
  - libvpx=1.11.0=h295c915_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.13=h1bed415_1
  - libxkbcommon=1.5.0=h79f4944_1
  - libxml2=2.10.3=hca2bb57_4
  - libzlib=1.2.13=h4ab18f5_6
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py311h5eee18b_0
  - matplotlib-inline=0.1.6=py311h06a4308_0
  - mistune=2.0.4=py311h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_1
  - mkl_fft=1.3.10=py311h5eee18b_0
  - mkl_random=1.2.7=py311ha02d727_0
  - moviepy=1.0.3=pyhd8ed1ab_1
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpg123=1.32.8=hc50e24c_0
  - mpmath=1.3.0=py311h06a4308_0
  - munkres=1.1.4=py_0
  - mysql=5.7.24=h721c034_2
  - mysql-common=8.0.32=ha901b37_0
  - mysql-libs=8.0.32=hd7da12d_0
  - nbclient=0.8.0=py311h06a4308_0
  - nbconvert=7.16.4=hd8ed1ab_1
  - nbconvert-core=7.16.4=pyhd8ed1ab_1
  - nbconvert-pandoc=7.16.4=hd8ed1ab_1
  - nbformat=5.10.4=py311h06a4308_0
  - ncurses=6.4.20240210=h59595ed_0
  - nest-asyncio=1.6.0=py311h06a4308_0
  - nettle=3.9.1=h7ab15ed_0
  - networkx=3.2.1=py311h06a4308_0
  - notebook=7.2.2=py311h06a4308_1
  - notebook-shim=0.2.3=py311h06a4308_0
  - nsight-compute=2024.1.1.4=0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numexpr=2.10.1=py311h3c60e43_0
  - numpy=1.26.4=py311h08b1b3b_0
  - numpy-base=1.26.4=py311hf175353_0
  - opencv=4.7.0=py311h38be061_1
  - openh264=2.3.1=hcb278e6_2
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.1.8=h7b32b05_0
  - overrides=7.4.0=py311h06a4308_0
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=24.1=py311h06a4308_0
  - pandoc=3.5=ha770c72_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=10.4.0=py311h5eee18b_0
  - pip=24.2=py311h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - pkgutil-resolve-name=1.3.10=py311h06a4308_1
  - platformdirs=3.10.0=py311h06a4308_0
  - ply=3.11=py311h06a4308_0
  - proglog=0.1.10=pyhaa61c55_0
  - prometheus_client=0.14.1=py311h06a4308_0
  - prompt-toolkit=3.0.43=py311h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py311h5eee18b_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pulseaudio=16.1=ha8d29e2_1
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-opencv=4.7.0=py311h781c19f_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py311h06a4308_1
  - pyparsing=3.1.2=py311h06a4308_0
  - pyqt=5.15.10=py311h6a678d5_0
  - pyqt5-sip=12.13.0=py311h5eee18b_0
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.0=he550d4f_1_cpython
  - python-dateutil=2.9.0post0=py311h06a4308_2
  - python-fastjsonschema=2.16.2=py311h06a4308_0
  - python-json-logger=2.0.7=py311h06a4308_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.11=5_cp311
  - pytorch=2.5.0=py3.11_cuda12.4_cudnn9.1.0_0
  - pytorch-cuda=12.4=hc786d27_7
  - pytorch-mutex=1.0=cuda
  - pytz=2024.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py311h5eee18b_0
  - pyzmq=25.1.2=py311h6a678d5_0
  - qhull=2020.2=hdb19cb5_2
  - qt-main=5.15.8=h5d23da1_6
  - qtconsole=5.6.0=py311h06a4308_0
  - qtconsole-base=5.6.0=pyha770c72_0
  - qtpy=2.4.1=py311h06a4308_0
  - readline=8.2=h5eee18b_0
  - referencing=0.30.2=py311h06a4308_0
  - requests=2.32.3=py311h06a4308_1
  - rfc3339-validator=0.1.4=py311h06a4308_0
  - rfc3986-validator=0.1.1=py311h06a4308_0
  - rpds-py=0.10.6=py311h4aa5aa6_1
  - safetensors=0.4.5=py311h448de89_1
  - send2trash=1.8.2=py311h06a4308_0
  - setuptools=75.1.0=py311h06a4308_0
  - sip=6.7.12=py311h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.3.0=py311h06a4308_0
  - soupsieve=2.5=py311h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - svt-av1=1.4.1=hcb278e6_0
  - sysroot_linux-64=2.17=h57e8cba_10
  - tbb=2021.8.0=hdb19cb5_0
  - terminado=0.17.1=py311h06a4308_0
  - timm=1.0.11=pyhd8ed1ab_0
  - tinycss2=1.2.1=py311h06a4308_0
  - tk=8.6.14=h39e8969_0
  - tomli=2.1.0=pyhff2d567_0
  - torchaudio=2.5.0=py311_cu124
  - torchinfo=1.8.0=pyhd8ed1ab_0
  - torchtriton=3.1.0=py311
  - torchvision=0.15.2=cuda118py311h4cc2eb7_0
  - tornado=6.4.1=py311h5eee18b_0
  - tqdm=4.66.5=py311h92b7b1e_0
  - traitlets=5.14.3=py311h06a4308_0
  - types-python-dateutil=2.9.0.20241003=pyhff2d567_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - unicodedata2=15.1.0=py311h5eee18b_0
  - uri-template=1.3.0=pyhd8ed1ab_0
  - urllib3=2.2.3=py311h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py311h06a4308_1
  - websocket-client=1.8.0=py311h06a4308_0
  - wheel=0.44.0=py311h06a4308_0
  - widgetsnbextension=4.0.13=pyhd8ed1ab_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.0=h516909a_0
  - xcb-util-image=0.4.0=h166bdaf_0
  - xcb-util-keysyms=0.4.0=h516909a_0
  - xcb-util-renderutil=0.3.9=h166bdaf_0
  - xcb-util-wm=0.4.1=h516909a_0
  - xkeyboard-config=2.38=h0b41bf4_0
  - xorg-fixesproto=5.0=hb9d3cd8_1003
  - xorg-inputproto=2.3.2=hb9d3cd8_1003
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.1=hb9d3cd8_1
  - xorg-libsm=1.2.4=he73a12e_1
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.11=hb9d3cd8_1
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xproto=7.0.31=h27cfd23_1007
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.21.0=pyhd8ed1ab_0
  - zlib=1.2.13=h4ab18f5_6
  - zstandard=0.23.0=py311h2c38b39_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - absl-py==2.1.0
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aiosignal==1.3.1
      - anndata==0.10.9
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - array-api-compat==1.9
      - astroid==3.3.5
      - autopep8==2.3.1
      - av==14.4.0
      - beartype==0.19.0
      - braceexpand==0.1.7
      - cfgv==3.4.0
      - cityscapesscripts==2.2.4
      - clean-fid==0.1.35
      - click==8.1.7
      - colored==2.2.4
      - coloredlogs==15.0.1
      - colorlog==6.9.0
      - datasets==3.0.2
      - diffusers==0.35.1
      - dill==0.3.8
      - distlib==0.4.0
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - einops==0.8.0
      - flake8==7.1.1
      - flow-vis==0.1
      - flowvid==0.4.1
      - frozenlist==1.5.0
      - ftfy==6.3.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - grpcio==1.67.0
      - h5py==3.12.1
      - hf-xet==1.1.10
      - holistictraceanalysis==0.5.0
      - huggingface-hub==0.35.0
      - humanfriendly==10.0
      - humanize==4.11.0
      - hydra-core==1.3.2
      - identify==2.6.13
      - iniconfig==2.1.0
      - ipycanvas==0.14.1
      - isort==5.13.2
      - jiter==0.8.2
      - joblib==1.4.2
      - lazy-loader==0.4
      - legacy-api-wrap==1.4
      - lightning-bolts==0.7.0
      - lightning-utilities==0.11.8
      - llvmlite==0.43.0
      - lpips==0.1.4
      - markdown==3.7
      - matplotlib==3.7.3
      - matplotlib2tikz==0.7.6
      - mccabe==0.7.0
      - mediapy==1.2.2
      - multidict==6.1.0
      - multiprocess==0.70.16
      - narwhals==1.43.1
      - natsort==8.4.0
      - nodeenv==1.9.1
      - numba==0.60.0
      - omegaconf==2.3.0
      - openai==1.59.9
      - pandas==2.0.3
      - pastel==0.2.1
      - patsy==0.5.6
      - plotly==6.1.2
      - pluggy==1.6.0
      - poethepoet==0.10.0
      - pot==0.9.4
      - pre-commit==4.3.0
      - prettytable==3.12.0
      - propcache==0.2.0
      - protobuf==5.28.3
      - ptflops==0.7.4
      - pyarrow==17.0.0
      - pycodestyle==2.12.1
      - pydantic==2.10.5
      - pydantic-core==2.27.2
      - pydot==4.0.1
      - pyflakes==3.2.0
      - pylint==3.3.1
      - pynndescent==0.5.13
      - pyquaternion==0.9.9
      - pytest==8.4.1
      - pytorch-lightning==1.9.5
      - pywavelets==1.8.0
      - qrcode==8.2
      - regex==2024.9.11
      - scanpy==1.10.3
      - scikit-image==0.24.0
      - scikit-learn==1.7.1
      - scipy==1.15.2
      - scprep==1.2.3
      - seaborn==0.13.2
      - sentry-sdk==2.17.0
      - session-info==1.0.0
      - setproctitle==1.3.3
      - slurm-gpustat==0.0.15
      - smmap==5.0.1
      - statsmodels==0.14.4
      - stdlib-list==0.11.0
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - termcolor==2.5.0
      - thop==0.1.1-2209072238
      - threadpoolctl==3.5.0
      - tifffile==2025.3.13
      - tikzplotlib==0.10.1
      - tokenizers==0.20.1
      - tomlkit==0.13.2
      - torch-tb-profiler==0.4.3
      - torchcde==0.2.5
      - torchcfm==1.0.5
      - torchdiffeq==0.2.4
      - torchdyn==1.0.6
      - torchmetrics==1.5.1
      - torchsde==0.2.6
      - trampoline==0.1.2
      - transformers==4.45.2
      - typing==3.7.4.3
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - umap-learn==0.5.6
      - virtualenv==20.34.0
      - wandb==0.20.0
      - webcolors==24.11.1
      - webdataset==0.2.100
      - werkzeug==3.0.6
      - xxhash==3.5.0
      - yarl==1.16.0
prefix: /athenahomes/gabrijel/miniconda3/envs/track-generator
